num1 = int(input("Enter the first number: ")) 
num2 = int(input("Enter the second number: "))
addition = int(num1) + int(num2) 
print("The addition of the numbers are: ", addition) 
subtract = int(num1) - int(num2)
print("The subtraction of the numbers are: ", subtract) 
multiply = int(num1) * int(num2)
print("The multiplication of the numbers are: ", multiply)
intDivision = int(num1) // int(num2)
floatDivision = float(num1) / float(num2)
print("The integer and float division of the numbers are: ", intDivision," and ", floatDivision) 
mod = float(num1) % float(num2)
print("The modulus of the numbers are: ", mod) 